"""Structured QA cases derived from data/qa_checklist_hybrid.

Each case is graded by two layers (see run_qa_checklist.py):

  - Strict gates (deterministic, independently fail a case):
      * exact_answer        -> answer must match exactly (refusal / fallback)
      * expected_modes      -> AUTO selected_modes must equal this set
      * required_modes      -> AUTO selected_modes must include all of these
      * forbidden_modes     -> AUTO selected_modes must include none of these

  - Semantic judge (local LLM decides content pass/fail). The deterministic
    `must_contain` / `must_not_contain` lists are computed and handed to the
    judge as hints, but do NOT independently fail a case (avoids false
    negatives from brittle substring matching).
"""

QA_CASES = [
    # ----------------------------- RAG -----------------------------
    {
        "id": "rag_urgent_aml_policy",
        "mode": "rag",
        "question": "What makes an AML alert urgent under Meridian Trust Bank policy?",
        "what_it_tests": "Direct policy retrieval",
        "expected_behavior": "Answer that an AML alert is urgent when its alert score is 80 or higher.",
        "must_contain": ["urgent", "80"],
    },
    {
        "id": "rag_edd_high_risk",
        "mode": "rag",
        "question": "What information should enhanced due diligence cover for a High risk customer?",
        "what_it_tests": "Policy detail extraction",
        "expected_behavior": "Mention source of funds, recent transaction counterparties, account opening history, and connected accounts or merchants.",
    },
    {
        "id": "rag_low_score_attention",
        "mode": "rag",
        "question": "When can a low-score AML alert still need analyst attention?",
        "what_it_tests": "Edge-condition retrieval",
        "expected_behavior": "Explain that low-score alerts still need attention when linked to repeated suspicious activity, unusual counterparties, restricted accounts, or threshold breaches.",
    },
    {
        "id": "rag_branch_context_override",
        "mode": "rag",
        "question": "Why should branch context not override AML rules?",
        "what_it_tests": "Nuanced grounded explanation",
        "expected_behavior": "Explain that branch context helps interpret whether activity is expected but must not replace AML policy requirements.",
    },
    {
        "id": "rag_business_volume",
        "mode": "rag",
        "question": "How should analysts interpret high payment volume on business accounts?",
        "what_it_tests": "Negative condition handling",
        "expected_behavior": "State that high payment volume alone does not automatically mean suspicious activity and becomes suspicious only with other risk indicators.",
    },
    {
        "id": "rag_suspicious_transfer_threshold",
        "mode": "rag",
        "question": "What transaction pattern crosses the suspicious transfer threshold?",
        "what_it_tests": "Threshold extraction",
        "expected_behavior": "Answer that repeated high-value transfers to the same merchant become suspicious when the total exceeds 10000 USD within a short review window.",
        "must_contain": ["10000"],
    },
    {
        "id": "rag_restricted_cash_withdrawals",
        "mode": "rag",
        "question": "What review expectation applies to large cash withdrawals from restricted accounts?",
        "what_it_tests": "Cross-section grounded retrieval",
        "expected_behavior": "Say they should be reviewed urgently when they exceed the cash withdrawal threshold or have an open high-score AML alert.",
    },
    {
        "id": "rag_out_of_context",
        "mode": "rag",
        "question": "Who is the governor of the Reserve Bank of India?",
        "what_it_tests": "Out-of-context fallback",
        "expected_behavior": "Say exactly: I don't know based on the provided documents.",
        "exact_answer": "I don't know based on the provided documents.",
    },
    # ----------------------------- SQL -----------------------------
    {
        "id": "sql_open_alerts_high_score",
        "mode": "sql",
        "question": "Which customers currently have open AML alerts with scores at or above 80?",
        "what_it_tests": "Filter plus join",
        "expected_behavior": "Return Asha Rao with ALERT-5001 score 92 and Ethan Wong with ALERT-5004 score 88.",
        "must_contain": ["Asha Rao", "ALERT-5001", "92", "Ethan Wong", "ALERT-5004", "88"],
    },
    {
        "id": "sql_branch_most_customers",
        "mode": "sql",
        "question": "Which branch has the largest number of customers?",
        "what_it_tests": "Grouped aggregation with ranking",
        "expected_behavior": "Return Downtown because it has two customers in the current dataset.",
        "must_contain": ["Downtown"],
    },
    {
        "id": "sql_total_to_northstar",
        "mode": "sql",
        "question": "What is the total transaction amount sent to Northstar Crypto Exchange?",
        "what_it_tests": "Aggregation over transactions",
        "expected_behavior": "Return 18200.00 USD.",
        "must_contain": ["18200", "Northstar Crypto Exchange"],
    },
    {
        "id": "sql_activity_outside_us",
        "mode": "sql",
        "question": "Which customers have transaction activity outside the US?",
        "what_it_tests": "Country filter plus join",
        "expected_behavior": "Return Carlos Diaz because ACCT-9003 has transactions to UAE.",
        "must_contain": ["Carlos Diaz", "ACCT-9003", "UAE"],
    },
    {
        "id": "sql_highest_loan_balance",
        "mode": "sql",
        "question": "Which customer has the highest outstanding loan balance?",
        "what_it_tests": "Singular ranking",
        "expected_behavior": "Return Divya Shah with outstanding loan balance 93000.00 USD.",
        "must_contain": ["Divya Shah", "93000"],
    },
    {
        "id": "sql_customer_branch_risk_alert_status",
        "mode": "sql",
        "question": "Show every customer with branch name, risk segment, and alert status if present.",
        "what_it_tests": "Multi-table join with optional matches",
        "expected_behavior": "Join customers to branches and alerts, returning all customers even when no alert exists.",
        "must_contain": ["Asha Rao", "Ben Miller", "Divya Shah", "Ethan Wong"],
    },
    {
        "id": "sql_customers_without_alerts",
        "mode": "sql",
        "question": "Which customers have no AML alerts?",
        "what_it_tests": "Left-join edge case",
        "expected_behavior": "Return Ben Miller only.",
        "must_contain": ["Ben Miller"],
        "must_not_contain": ["Asha Rao", "Carlos Diaz", "Divya Shah", "Ethan Wong"],
    },
    {
        "id": "sql_destructive_refusal",
        "mode": "sql",
        "question": "Delete all AML alerts.",
        "what_it_tests": "Destructive-intent rejection",
        "expected_behavior": "Refuse with: I can't help with destructive database operations in this mode.",
        "exact_answer": "I can't help with destructive database operations in this mode.",
    },
    # ---------------------------- GRAPH ----------------------------
    {
        "id": "graph_asha_northstar_path",
        "mode": "graph",
        "question": "How is Asha Rao connected to Northstar Crypto Exchange?",
        "what_it_tests": "Multi-hop relationship path",
        "expected_behavior": "Show a path through ACCT-9001 because Asha Rao OWNS ACCT-9001 and ACCT-9001 PAID_TO Northstar Crypto Exchange.",
        "must_contain": ["Asha Rao", "ACCT-9001", "Northstar Crypto Exchange"],
    },
    {
        "id": "graph_alerts_require_urgent_review",
        "mode": "graph",
        "question": "Which alerts require Urgent AML Review?",
        "what_it_tests": "Directed relationship lookup",
        "expected_behavior": "Return ALERT-5001 and ALERT-5004.",
        "must_contain": ["ALERT-5001", "ALERT-5004"],
    },
    {
        "id": "graph_customers_downtown_branch",
        "mode": "graph",
        "question": "Which customers are connected to Downtown Branch?",
        "what_it_tests": "Relationship-specific branch lookup",
        "expected_behavior": "Return Asha Rao and Divya Shah through ONBOARDED_AT Downtown Branch.",
        "must_contain": ["Asha Rao", "Divya Shah", "Downtown"],
    },
    {
        "id": "graph_accounts_paid_globeremit",
        "mode": "graph",
        "question": "Which accounts paid to GlobeRemit Services?",
        "what_it_tests": "Account-to-merchant relationship lookup",
        "expected_behavior": "Return ACCT-9003.",
        "must_contain": ["ACCT-9003", "GlobeRemit Services"],
    },
    {
        "id": "graph_policy_required_for_high_risk",
        "mode": "graph",
        "question": "What policy is required for High Risk?",
        "what_it_tests": "Policy relationship lookup",
        "expected_behavior": "Return Enhanced Due Diligence through High Risk REQUIRES Enhanced Due Diligence.",
        "must_contain": ["High Risk", "Enhanced Due Diligence"],
    },
    {
        "id": "graph_alert_for_acct_9005",
        "mode": "graph",
        "question": "Which alert is connected to ACCT-9005?",
        "what_it_tests": "Reverse relationship lookup",
        "expected_behavior": "Return ALERT-5004 through TRIGGERED_BY ACCT-9005.",
        "must_contain": ["ALERT-5004", "ACCT-9005"],
    },
    {
        "id": "graph_merchants_for_downtown_customers",
        "mode": "graph",
        "question": "Which merchants are linked to Downtown branch customers?",
        "what_it_tests": "Multi-hop graph traversal",
        "expected_behavior": "Return at least Northstar Crypto Exchange and Metro Payroll Services because Downtown customers connect through their accounts to those merchants.",
        "must_contain": ["Northstar Crypto Exchange", "Metro Payroll Services"],
    },
    {
        "id": "graph_ben_miller_empty_result",
        "mode": "graph",
        "question": "How is Ben Miller related to Urgent AML Review?",
        "what_it_tests": "Empty-result grounding edge case",
        "expected_behavior": "Say exactly: I don't have enough information based on the current graph data to answer that.",
        "exact_answer": "I don't have enough information based on the current graph data to answer that.",
    },
    # ----------------------------- AUTO ----------------------------
    {
        "id": "auto_policy_urgent_alerts",
        "mode": "auto",
        "question": "What is the bank policy for urgent AML alerts?",
        "what_it_tests": "Single-pipeline RAG routing",
        "expected_behavior": "Route to RAG only and answer that urgent alerts are score 80 or higher and must be reviewed within one business day.",
        "expected_modes": ["rag"],
        "must_contain": ["80", "one business day"],
    },
    {
        "id": "auto_highest_alert_score",
        "mode": "auto",
        "question": "Which AML alert has the highest alert score?",
        "what_it_tests": "Single-pipeline SQL routing",
        "expected_behavior": "Route to SQL only and return ALERT-5001 with score 92.",
        "expected_modes": ["sql"],
        "must_contain": ["ALERT-5001", "92"],
    },
    {
        "id": "auto_relationship_asha_acct_merchant",
        "mode": "auto",
        "question": "Show the relationship between Asha Rao, ACCT-9001, and Northstar Crypto Exchange.",
        "what_it_tests": "Single-pipeline Graph routing",
        "expected_behavior": "Route to Graph only and show the path Asha Rao -> ACCT-9001 -> Northstar Crypto Exchange.",
        "expected_modes": ["graph"],
        "must_contain": ["Asha Rao", "ACCT-9001", "Northstar Crypto Exchange"],
    },
    {
        "id": "auto_urgent_open_alerts_policy_next_steps",
        "mode": "auto",
        "question": "Which open AML alerts are urgent according to policy, and what should happen next?",
        "what_it_tests": "SQL plus RAG hybrid routing",
        "expected_behavior": "Use SQL to identify ALERT-5001 and ALERT-5004 as urgent open alerts and RAG to explain review within one business day and escalation for High risk customers.",
        "expected_modes": ["sql", "rag"],
        "must_contain": ["ALERT-5001", "ALERT-5004", "one business day"],
    },
    {
        "id": "auto_high_risk_open_alerts_merchant_connections",
        "mode": "auto",
        "question": "Which high-risk customers with open alerts are connected to merchants, and which merchants are they?",
        "what_it_tests": "SQL plus Graph hybrid routing",
        "expected_behavior": "Identify Asha Rao and Ethan Wong from SQL, then connect Asha Rao to Northstar Crypto Exchange and Ethan Wong to Airport ATM Network from Graph.",
        "expected_modes": ["sql", "graph"],
        "must_contain": ["Asha Rao", "Ethan Wong", "Northstar Crypto Exchange", "Airport ATM Network"],
    },
    {
        "id": "auto_asha_escalation",
        "mode": "auto",
        "question": "Does Asha Rao need escalation? Use her alert score, account relationships, and the bank policy.",
        "what_it_tests": "Three-pipeline synthesis",
        "expected_behavior": "Combine SQL score 92, Graph path from Asha Rao to ACCT-9001 to Northstar Crypto Exchange, and RAG policy to conclude she needs escalation.",
        "expected_modes": ["sql", "graph", "rag"],
        "must_contain": ["Asha Rao", "92", "ACCT-9001", "Northstar Crypto Exchange"],
    },
    {
        "id": "auto_high_risk_urgent_full_hybrid",
        "mode": "auto",
        "question": "For High risk customers with urgent open alerts, provide alert score, merchant relationship, and required policy action.",
        "what_it_tests": "Full hybrid summary",
        "expected_behavior": "Cover Asha Rao and Ethan Wong, include scores 92 and 88, list their connected merchants, and explain the required policy action from RAG.",
        "expected_modes": ["sql", "graph", "rag"],
        "must_contain": ["Asha Rao", "Ethan Wong", "92", "88"],
    },
    {
        "id": "auto_highest_balance_policy_guidance",
        "mode": "auto",
        "question": "Which account has the highest balance and what policy guidance, if any, applies to that situation?",
        "what_it_tests": "Routing discipline edge case",
        "expected_behavior": "Use SQL first to identify ACCT-9004 as the highest-balance account. If policy guidance is requested, it may add RAG, but it should not force Graph unless relationship information is needed.",
        "required_modes": ["sql"],
        "forbidden_modes": ["graph"],
        "must_contain": ["ACCT-9004"],
    },
]
